baseURL = 'https://fairways.sirapollokaggwaschools.co.ug/'
locale = 'en-us'
title = 'Fairways Primary School - Kireka'

[module]
  [[module.imports]]
    path = 'github.com/sakschools/saks-shared-theme'

[params]
logo = "/img/logo.png"
mainSchool = false
github_repo = "saks-fairways"