baseURL = 'https://fairways.sirapollokaggwaschools.co.ug/'
languageCode = 'en-us'
title = 'Fairways Primary School - Kireka'
theme = "C:\\Users\\timot\\SAKS_web\\sirapollokaggwaschools\\themes\\saks-theme"

[params]
    mainSchool = false
    defaultDescription = "Fairways Primary School - Kireka (Day) is a private primary school registered with the ministry of education and sports with a UNEB centre number offering Education to Ugandan and non-Ugandan children based on the Ugandan Curriculum and equipping them with necessary life skills."
    [params.school]
        motto = 'We Ignite Academic Excellence'
        summary1 = 'Fairways Primary School - Kireka (Day) is a private primary school registered with the ministry of education and sports with a UNEB centre number offering Education to Ugandan and non-Ugandan children based on the Ugandan Curriculum and equipping them with necessary life skills.'
        summary2 = 'We provide a stimulating and credible learning environment which will produce dynamic and talented young Ugandan citizens and ensure all learners are equipped to meet the challenges of life”.'
